services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Tests\Behat\:
        resource: '../tests/Behat/*'

    ApiPlatform\Core\Bridge\Symfony\Bundle\Test\Client: '@test.api_platform.client'
